export const BRYANT_GOLD = "#C5A44E";

export const DOMAIN_OPTIONS = [
  { value: "Accounting", label: "Accounting" },
  { value: "Actuarial Mathematics", label: "Actuarial Mathematics" },
  { value: "Applied Analytics", label: "Applied Analytics" },
  { value: "Applied Economics", label: "Applied Economics" },
  { value: "Arts", label: "Arts" },
  { value: "Business", label: "Business" },
  { value: "Club Sports", label: "Club Sports" },
  { value: "Communication", label: "Communication" },
  { value: "Community Service", label: "Community Service" },
  { value: "Computer Science", label: "Computer Science" },
  { value: "Cybersecurity", label: "Cybersecurity" },
  { value: "Data Science", label: "Data Science" },
  { value: "Debate", label: "Debate" },
  { value: "Economics", label: "Economics" },
  { value: "Engineering", label: "Engineering" },
  { value: "Entrepreneurship", label: "Entrepreneurship" },
  { value: "Environmental Science", label: "Environmental Science" },
  { value: "Finance", label: "Finance" },
  { value: "Global Studies", label: "Global Studies" },
  { value: "Information Systems", label: "Information Systems" },
  { value: "International Business", label: "International Business" },
  { value: "Legal Studies", label: "Legal Studies" },
  { value: "Management", label: "Management" },
  { value: "Marketing", label: "Marketing" },
  { value: "Political Science", label: "Political Science" },
  { value: "Psychology", label: "Psychology" },
  { value: "Sociology", label: "Sociology" },
  { value: "Sports Analytics", label: "Sports Analytics" },
  { value: "Other", label: "Other" },
];
